## ================= Elastic Enterprise Search Configuration ==================
#
# NOTE: Elastic Enterprise Search comes with reasonable defaults.
#       Before adjusting the configuration, make sure you understand what you
#       are trying to accomplish and the consequences.
#
# NOTE: For passwords, the use of environment variables is encouraged
#       to keep values from being written to disk, e.g.
#       elasticsearch.password: ${ELASTICSEARCH_PASSWORD:changeme}
#
# ------------------------------- Elasticsearch -------------------------------
#
# Enterprise Search needs one-time permission to alter Elasticsearch settings.
# Ensure the Elasticsearch settings are correct, then set the following to
# true.
# Or, adjust Elasticsearch's config/elasticsearch.yml instead.
# See README.md for more details.
#
allow_es_settings_modification: true
#
# Elasticsearch full cluster URL:
#
elasticsearch.host: http://elasticsearch:9200
#
# Elasticsearch credentials:
#
elasticsearch.username: {{ elastic_username }}
elasticsearch.password: {{ elastic_password }}
#
# Elasticsearch custom HTTP headers to add to each request:
#
#elasticsearch.headers:
#  X-My-Header: Contents of the header
#
# Elasticsearch SSL settings:
#
#elasticsearch.ssl.enabled: false
#elasticsearch.ssl.certificate:
#elasticsearch.ssl.certificate_authority:
#elasticsearch.ssl.key:
#elasticsearch.ssl.key_passphrase:
#elasticsearch.ssl.verify: true
#
# ------------------------------- Hosting & Network ---------------------------
#
# Define the exposed URL at which users will reach Enterprise Search.
# Defaults to localhost:3002 for testing purposes.
# Most cases will use one of:
#
# * An IP: http://255.255.255.255
# * A FQDN: http://example.com
# * Shortname defined via /etc/hosts: http://ent-search.search
#
#ent_search.external_url: http://localhost:3002
#
# Web application listen_host and listen_port.
# Your application will run on this host and port.
#
# * ent_search.listen_host: Must be a valid IPv4 or IPv6 address.
# * ent_search.listen_port: Must be a valid port number (1-65535).
#
ent_search.listen_host: 0.0.0.0
ent_search.listen_port: 3002
#
# Background worker monitoring.
# Diagnostic information will be served on `ent_search.monitoring_port`.
#
# * ent_search.monitoring_enabled: Set to false to disable monitoring.
# * ent_search.monitoring_port: Must be a valid port number (1-65535).
#
ent_search.monitoring_enabled: true
ent_search.monitoring_port: 3003
#
# ------------------------------ Authentication -------------------------------
#
# The origin of authenticated Enterprise Search users.
# Options are standard, elasticsearch-native, and elasticsearch-saml.
#
# Docs: https://swiftype.com/documentation/enterprise-search/guides/user-management
#
# * standard: Users are created within the Enterprise Search dashboard.
# * elasticsearch-native: Users are managed via the Elasticsearch native realm.
# * elasticsearch-saml: Users are managed via the Elasticsearch SAML realm.
#
#ent_search.auth.source: standard
#
# (SAML only) Name of the realm within the Elasticsearch realm chain.
#
#ent_search.auth.name:
#
# ---------------------------------- Workers ----------------------------------
#
# Configure the number of worker threads.
#
#worker.threads: 4
#
# ----------------------------------- APIs ------------------------------------
#
# Set to true hide product version information from API responses.
#
#hide_version_info: false
#
# ---------------------------------- Mailer -----------------------------------
#
# Connect Enterprise Search to a mailer.
# Docs: https://swiftype.com/documentation/enterprise-search/guides/smtp-mailer
#
#email.account.enabled: false
#email.account.smtp.auth: plain
#email.account.smtp.starttls.enable: false
#email.account.smtp.host: 127.0.0.1
#email.account.smtp.port: 25
#email.account.smtp.user:
#email.account.smtp.password:
#email.account.email_defaults.from:
#
# ---------------------------------- Logging ----------------------------------
#
# Choose your log export path.
#
#log_directory: log
#
# Log level can be: debug, info, warn, error, fatal, or unknown.
#
#log_level: info
#
# Log format can be: default, json
#
#log_format: default
#
# Choose your Filebeat logs export path.
#
#filebeat_log_directory: log
#
# ---------------------------------- TLS/SSL ----------------------------------
#
# Configure TLS/SSL encryption.
#
#ent_search.ssl.enabled: false
#ent_search.ssl.keystore.path:
#ent_search.ssl.keystore.password:
#ent_search.ssl.keystore.key_password:
#ent_search.ssl.redirect_http_from_port:
#
# Worker monitoring server ssl options
#
#ent_search.monitoring_ssl.enabled: false
#ent_search.monitoring_ssl.certificate:
#ent_search.monitoring_ssl.certificate_authority:
#ent_search.monitoring_ssl.key:
#ent_search.monitoring_ssl.key_passphrase:
#ent_search.monitoring_ssl.verify: true
#
# ---------------------------------- Secrets ----------------------------------
# Set to decrypt session information through restarts. Key can be supplied
# by you, or you can use the generated key provided during binary startup.
#
secret_management.encryption_keys: [6f85f87e4c82859415bbe6da78afc9c6c8b2082de8db075667530ca81ee5e971]
#
# ---------------------------------- Session ----------------------------------
#
# Set key to persist user sessions through process restarts.
#
secret_session_key: 53bedaf7f4639f6fd17149079d919f55fe0d69ea2539e735e31d6e32c00acf692e74160a244e99a69b7e6b9ce84ad365777e8a92d01169cc3914e8602c70460e
