#============================== Log sources ===================================

filebeat.inputs:
- type: log
  enabled: true
  json.message_key:
  json.keys_under_root: true
  json.overwrite_keys: true # get timestamp from the log, etc
  # ENT_SEARCH_FILEBEAT_LOGS will be set to the value of `filebeat_log_directory`
  # in config/enterprise-search.yml
  paths:
    - ${ENT_SEARCH_FILEBEAT_LOGS}/logstasher.log

#================================ Outputs ======================================

# Configure what output to use when sending the data collected by the beat.

#-------------------------- Elasticsearch output -------------------------------
output.elasticsearch:
  # Array of hosts to connect to.
  # Scheme and port can be left out and will be set to the default (http and 9200)
  # In case you specify an additional path, the scheme is required: http://localhost:9200/path
  # IPv6 addresses should always be defined as: https://[2001:db8::1]:9200
  # ELASTICSEARCH_HOST will be set to the value of `elasticsearch.host` in config/enterprise-search.yml
  hosts: ["${ELASTICSEARCH_HOST}"]

  # Optional protocol and basic auth credentials.
  #protocol: "https"

  # ELASTICSEARCH_USERNAME and ELASTICSEARCH_PASSWORD will be set to the values of
  # `elasticsearch.username` and `elasticsearch.password`, respectively, in config/enterprise-search.yml
  username: "${ELASTICSEARCH_USERNAME}"
  password: "${ELASTICSEARCH_PASSWORD}"

  # Custom HTTP headers are set to the values of `elasticsearch.headers` in config/enterprise-search.yml
  headers: ${ELASTICSEARCH_HEADERS}

  # SSL variables are set to the values of `elasticsearch.ssl` in config/enterprise-search.yml
  ssl: ${ELASTICSEARCH_SSL}

  # Optional index name. The default is "filebeat" plus date
  # and generates [filebeat-]YYYY.MM.DD keys.
  # In case you modify this pattern you must update setup.template.name and setup.template.pattern accordingly.
  index: ".ent-search-app-logs-${RAILS_ENV:development}-%{[agent.version]}-%{+yyyy.MM.dd}"
  indices:
    - index: ".ent-search-analytics-logs-${RAILS_ENV:development}-%{[agent.version]}-%{+yyyy.MM.dd}"
      when.equals:
        "@source": "analytics"

#============================== Setup ILM =====================================

setup.ilm.enabled: false

#==================== Elasticsearch template setting ==========================

setup.template.name: "ent-search-logs"
setup.template.pattern: ".ent-search-*-logs-*"
setup.template.json.enabled: true
setup.template.json.path: "${FILEBEAT_DIR}/filebeat-template.json"
setup.template.json.name: "ent-search-logs"

#================================= Paths ======================================

# The home path for the filebeat installation. This is the default base path
# for all other path settings and for miscellaneous files that come with the
# distribution (for example, the sample dashboards).
# If not set by a CLI flag or in the configuration file, the default for the
# home path is the location of the binary.
path.home: ${FILEBEAT_DIR}

# The configuration path for the filebeat installation. This is the default
# base path for configuration files, including the main YAML configuration file
# and the Elasticsearch template file. If not set by a CLI flag or in the
# configuration file, the default for the configuration path is the home path.
#path.config: ${path.home}

# The data path for the filebeat installation. This is the default base path
# for all the files in which filebeat needs to store its data. If not set by a
# CLI flag or in the configuration file, the default for the data path is a data
# subdirectory inside the home path.
#path.data: ${path.home}/data

# The logs path for a filebeat installation. This is the default location for
# the Beat's log files. If not set by a CLI flag or in the configuration file,
# the default for the logs path is a logs subdirectory inside the home path.
# ENT_SEARCH_FILEBEAT_LOGS will be set to the value of `filebeat_log_directory`
# in config/enterprise-search.yml
path.logs: ${ENT_SEARCH_FILEBEAT_LOGS}
