---
vars:
  passwords:
    elastic_password: '{{ item.elastic }}'
    kibana_password: '{{ item.kibana }}'
    apm_system_password: '{{ item.apm_system }}'
    logstash_system_password: '{{ item.logstash_system }}'
    beats_system_password: '{{ item.beats_system }}'
    remote_monitoring_user_password: '{{ item.remote_monitoring_user }}'

keys:
  list:
    value: "{{ passwords }}"
    items: "^.+apm_system\\s?=\\s?(?P<apm_system>\\S+).+kibana\\s?=\\s?(?P<kibana>\\S+).+logstash_system\\s?=\\s?(?P<logstash_system>\\S+).+beats_system\\s?=\\s?(?P<beats_system>\\S+).+remote_monitoring_user\\s?=\\s?(?P<remote_monitoring_user>\\S+).+elastic\\s?=\\s?(?P<elastic>\\S+)"
